import { TableType } from './monitor.types';

const contestDefault = {
  id: 0,
  workshop_id: 0,
  position: 1,
  time_start: 'string',
  time_stop: 'string',
  is_virtual: false,
  virtual_duration: 0,
}

const dataDefault = {
  contests: [
    {
      ...contestDefault,
      statement: {
        id: 1,
        name: 'День 1. Разгоночный контест на графы',
        summary: 'Описание контеста и время проведения при необходимости',
        problems: [
          {
            id: 3234,
            name: 'Парк аттракционов',
            rank: 1,
          },
          {
            id: 3235,
            name: 'Парк аттракционов',
            rank: 2,
          },
          {
            id: 3236,
            name: 'Парк аттракционов',
            rank: 3,
          },
          {
            id: 3237,
            name: 'Парк аттракционов',
            rank: 4,
          },
          {
            id: 3238,
            name: 'Парк аттракционов',
            rank: 5,
          },
          {
            id: 3239,
            name: 'Парк аттракционов',
            rank: 6,
          },
        ],
      },
    }, {
      ...contestDefault,
      statement: {
        id: 2,
        name: 'День 2. Разгоночный контест на графы',
        summary: 'Описание контеста и время проведения при необходимости',
        problems: [
          {
            id: 3240,
            name: 'Парк аттракционов',
            rank: 1,
          },
          {
            id: 3241,
            name: 'Парк аттракционов',
            rank: 2,
          },
          {
            id: 3242,
            name: 'Парк аттракционов',
            rank: 3,
          },
          {
            id: 3243,
            name: 'Парк аттракционов',
            rank: 4,
          },
          {
            id: 3244,
            name: 'Парк аттракционов',
            rank: 5,
          },
          {
            id: 3245,
            name: 'Парк аттракционов',
            rank: 6,
          },
        ],
      },
    },
  ],
  users: [
    {
      id: 0,
      firstname: 'Иван',
      lastname: 'Андронов',
    },
    {
      id: 1,
      firstname: 'Константин',
      lastname: 'Бровкин',
    },
    {
      id: 2,
      firstname: 'Александр',
      lastname: 'Барсуков',
    },
    {
      id: 3,
      firstname: 'Иван',
      lastname: 'Вандронов',
    },
    {
      id: 4,
      firstname: 'Самуил',
      lastname: 'Гровкин',
    },
  ],
  results: {
    0: {
      3234: {
        on_testing: false,
        is_ignored: false,
        mark: '100',
        time: 124500,
        success: true,
        wrong_tries: 2,
      },
      3235: {
        on_testing: false,
        is_ignored: false,
        mark: '88',
        time: 112300,
        success: true,
        wrong_tries: 0,
      },
      3236: {
        on_testing: false,
        is_ignored: false,
        mark: '91',
        time: 169800,
        success: true,
        wrong_tries: 1,
      },
      3237: {
        on_testing: false,
        is_ignored: false,
        mark: '61',
        time: 173800,
        success: true,
        wrong_tries: 3,
      },
      3238: {
        on_testing: false,
        is_ignored: false,
        mark: '94.25',
        time: 58800,
        success: true,
        wrong_tries: 2,
      },
      3239: {
        on_testing: false,
        is_ignored: false,
        mark: '55',
        time: 336000,
        success: true,
        wrong_tries: 0,
      },
      3240: {
        on_testing: false,
        is_ignored: false,
        mark: '92',
        time: 169800,
        success: true,
        wrong_tries: 4,
      },
      3241: {
        on_testing: false,
        is_ignored: false,
        mark: '61',
        time: 173800,
        success: true,
        wrong_tries: 1,
      },
      3242: {
        on_testing: false,
        is_ignored: false,
        mark: '94.25',
        time: 58800,
        success: true,
        wrong_tries: 2,
      },
      3243: {
        on_testing: false,
        is_ignored: false,
        mark: '55',
        time: 336000,
        success: true,
        wrong_tries: 3,
      },
      3244: {
        on_testing: false,
        is_ignored: false,
        mark: '100',
        time: 124500,
        success: true,
        wrong_tries: 0,
      },
      3245: {
        on_testing: false,
        is_ignored: false,
        mark: '100',
        time: 124500,
        success: true,
        wrong_tries: 1,
      },
    },
    1: {
      3234: {
        on_testing: false,
        is_ignored: false,
        mark: '92',
        time: 122400,
        success: true,
        wrong_tries: 1,
      },
      3235: {
        on_testing: false,
        is_ignored: false,
        mark: '88',
        time: 282300,
        success: true,
        wrong_tries: 2,
      },
      3236: {
        on_testing: false,
        is_ignored: false,
        mark: '21',
        time: 200800,
        success: true,
        wrong_tries: 0,
      },
      3237: {
        on_testing: false,
        is_ignored: false,
        mark: '31',
        time: 376800,
        success: true,
        wrong_tries: 4,
      },
      3238: {
        on_testing: true,
        is_ignored: false,
        mark: '',
        time: 0,
        success: false,
        wrong_tries: 1,
      },
      3239: {
        on_testing: false,
        is_ignored: false,
        mark: '99',
        time: 297000,
        success: true,
        wrong_tries: 3,
      },
      3240: null,
      3241: {
        on_testing: false,
        is_ignored: false,
        mark: '87',
        time: 173800,
        success: true,
        wrong_tries: 0,
      },
      3242: {
        on_testing: false,
        is_ignored: false,
        mark: '94.25',
        time: 58800,
        success: true,
        wrong_tries: 2,
      },
      3243: {
        on_testing: false,
        is_ignored: false,
        mark: '55',
        time: 336000,
        success: true,
        wrong_tries: 3,
      },
      3244: {
        on_testing: false,
        is_ignored: false,
        mark: '100',
        time: 124500,
        success: true,
        wrong_tries: 1,
      },
      3245: {
        on_testing: false,
        is_ignored: false,
        mark: '100',
        time: 124500,
        success: true,
        wrong_tries: 4,
      },
    },
    2: {
      3234: {
        on_testing: false,
        is_ignored: false,
        mark: '69',
        time: 124500,
        success: true,
        wrong_tries: 3,
      },
      3235: {
        on_testing: false,
        is_ignored: false,
        mark: '75',
        time: 112300,
        success: true,
        wrong_tries: 0,
      },
      3236: {
        on_testing: false,
        is_ignored: false,
        mark: '89',
        time: 169800,
        success: true,
        wrong_tries: 2,
      },
      3237: {
        on_testing: false,
        is_ignored: true,
        mark: '',
        time: 416700,
        success: false,
        wrong_tries: 2,
      },
      3238: {
        on_testing: false,
        is_ignored: false,
        mark: '87',
        time: 58800,
        success: true,
        wrong_tries: 1,
      },
      3239: {
        on_testing: false,
        is_ignored: false,
        mark: '88',
        time: 336000,
        success: true,
        wrong_tries: 1,
      },
      3240: {
        on_testing: false,
        is_ignored: false,
        mark: '34',
        time: 169800,
        success: false,
        wrong_tries: 0,
      },
      3241: {
        on_testing: false,
        is_ignored: false,
        mark: '61',
        time: 173800,
        success: true,
        wrong_tries: 1,
      },
      3242: {
        on_testing: false,
        is_ignored: false,
        mark: '94.25',
        time: 58800,
        success: true,
        wrong_tries: 1,
      },
      3243: {
        on_testing: false,
        is_ignored: false,
        mark: '55',
        time: 336000,
        success: true,
        wrong_tries: 0,
      },
      3244: {
        on_testing: false,
        is_ignored: false,
        mark: '100',
        time: 124500,
        success: true,
        wrong_tries: 1,
      },
      3245: {
        on_testing: false,
        is_ignored: false,
        mark: '100',
        time: 124500,
        success: true,
        wrong_tries: 2,
      },
    },
    3: {
      3234: {
        on_testing: false,
        is_ignored: false,
        mark: '89',
        time: 124500,
        success: true,
        wrong_tries: 0,
      },
      3235: {
        on_testing: false,
        is_ignored: false,
        mark: '65',
        time: 112300,
        success: true,
        wrong_tries: 1,
      },
      3236: {
        on_testing: false,
        is_ignored: false,
        mark: '88',
        time: 169800,
        success: true,
        wrong_tries: 1,
      },
      3237: {
        on_testing: false,
        is_ignored: false,
        mark: '56',
        time: 173800,
        success: true,
        wrong_tries: 0,
      },
      3238: {
        on_testing: false,
        is_ignored: false,
        mark: '70',
        time: 58800,
        success: true,
        wrong_tries: 2,
      },
      3239: {
        on_testing: false,
        is_ignored: false,
        mark: '81',
        time: 336000,
        success: true,
        wrong_tries: 0,
      },
      3240: {
        on_testing: false,
        is_ignored: false,
        mark: '92',
        time: 169800,
        success: true,
        wrong_tries: 0,
      },
      3241: {
        on_testing: false,
        is_ignored: false,
        mark: '61',
        time: 173800,
        success: true,
        wrong_tries: 1,
      },
      3242: {
        on_testing: false,
        is_ignored: false,
        mark: '94.25',
        time: 58800,
        success: true,
        wrong_tries: 0,
      },
      3243: {
        on_testing: false,
        is_ignored: false,
        mark: '55',
        time: 336000,
        success: true,
        wrong_tries: 1,
      },
      3244: {
        on_testing: false,
        is_ignored: false,
        mark: '100',
        time: 124500,
        success: true,
        wrong_tries: 0,
      },
      3245: {
        on_testing: false,
        is_ignored: false,
        mark: '100',
        time: 124500,
        success: true,
        wrong_tries: 0,
      },
    },
    4: {
      3234: {
        on_testing: false,
        is_ignored: false,
        mark: '92',
        time: 122400,
        success: true,
        wrong_tries: 2,
      },
      3235: {
        on_testing: false,
        is_ignored: false,
        mark: '88',
        time: 282300,
        success: true,
        wrong_tries: 3,
      },
      3236: {
        on_testing: false,
        is_ignored: false,
        mark: '21',
        time: 200800,
        success: true,
        wrong_tries: 1,
      },
      3237: null,
      3238: null,
      3239: null,
      3240: {
        on_testing: false,
        is_ignored: false,
        mark: '80',
        time: 297000,
        success: true,
        wrong_tries: 0,
      },
      3241: {
        on_testing: false,
        is_ignored: false,
        mark: '87',
        time: 173800,
        success: true,
        wrong_tries: 1,
      },
      3242: {
        on_testing: false,
        is_ignored: false,
        mark: '94.25',
        time: 58800,
        success: true,
        wrong_tries: 1,
      },
      3243: {
        on_testing: false,
        is_ignored: false,
        mark: '55',
        time: 336000,
        success: true,
        wrong_tries: 1,
      },
      3244: {
        on_testing: false,
        is_ignored: false,
        mark: '100',
        time: 124500,
        success: true,
        wrong_tries: 2,
      },
      3245: {
        on_testing: false,
        is_ignored: false,
        mark: '100',
        time: 124500,
        success: true,
        wrong_tries: 0,
      },
    },
  },
};


export const dataIOI = {
  ...dataDefault,
  type: TableType.IOI,
};

export const dataACM = {
  ...dataDefault,
  type: TableType.ACM,
};

export const dataLightACM = {
  ...dataDefault,
  type: TableType.LightACM,
};
